### ISSUE TITLE
Clear Install - BUG at start

### ISSUE THREAD

**Issue by ffdown** [butaixianran/Stable-Diffusion-Webui-Post-Face-Restore-Again#1]
```
Error loading script: postprocessing_facerestore.py
Traceback (most recent call last):
  File "E:\AI\SD\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "E:\AI\SD\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "E:\AI\SD\stable-diffusion-webui\scripts\postprocessing_facerestore.py", line 5, in <module>
    from modules import scripts_postprocessing, gfpgan_model
ImportError: cannot import name 'scripts_postprocessing' from 'modules' (unknown location)
```

install in <script> or install in extension tab no difference

**Comment by butaixianran** [comment]
Hi, scripts_postprocessing is a build-in file under modules folder. If you do not have this file, that means you failed when install stable-diffusion-webui. There are many build-in feature need this file.

This means, you don't even download stable-diffusion-webui right. Can you really run stable-diffusion-webui?

**Comment by ffdown** [comment]
webui, I usually linger on everything from the moment it appeared ... strange doubts. All started give me a screen where find your checkbox

**Comment by butaixianran** [comment]
Like I said, scripts_postprocessing is a build in file. When you download webui, it will come with it.

You do not have it, that means you download it wrong.

You can find this file in webui's official project, it's there:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/scripts_postprocessing.py

Check if this file is under your webui's modules folder.

And if you can see this extension's checkbox on webui's page, it is already running.

And if you are chinese, try not use third part package to run your webui. Run it under its own env.
